### ISSUE TITLE
Changes to Ecobe authentication

### ISSUE THREAD

**Issue by Gruski** [i8beef/Ecobee#11]
Are there any plans to update this API to the new authentication scheme that Ecobee just put in place?

**Comment by i8beef** [comment]
Have you tried it? I don't actually believe any changes are necessary here. They haven't changed any contracts, just how they generate the token strings. When they make the switch your old tokens will be no good so you'll have to reauth with the PIN, but it should just work after that I believe.

**Comment by Gruski** [comment]
It looks like they already made the switch because the code has been broken since about 5 days ago. I deleted the old tokens and attempted to retokenize. I get the following exception from your API now:
"The grant, token or credentials are invalid, expired, revoked, do not match redirection URI used in the authorization request, or was issued to another client."

These are the items they claim have changed:

- Access tokens will be up to 7KB in length, and includes upper/lower case alphanumeric characters, hyphens, underscores, and periods.
- Refresh tokens can be of varying lengths and can contain non-alphanumeric characters.
- The Redirect URI associated with your registered application should be a semi-colon separated list of absolute URLs that start with https://. We do not accept http://  protocol links.

One of these must be braking the code.

**Comment by Gruski** [comment]
I tested again today and now it's working. I'll let you know if it breaks again.

**Comment by i8beef** [comment]
Glad to hear you got it working. That ought to be the case given their documented changes.

They have claimed they aren't making this change until December though. I don't think you should be seeing a change yet anyway, as I think there'd have to be a change to the URL this library requests for auth to request the JWT change early... are oyu sure your token didn't just get invalidated on you early?

**Comment by Gruski** [comment]
Possibly but that has never happened before and I've had my app running for years. It wasn't enough to renew all the tokens. What fixed it was I had to remove the app registration from their web interface and recreate it. We'll see if anything breaks in December.

**Comment by i8beef** [comment]
That would make sense. Once your tokens are out of sync, the only way to get back would be to relink. I HAVE had my tokens get messed up a few times, like once a year or so probably, but that's obviously hard to track down since its so rare (and could be caused by so many different things, including Ecobee's side forgetting or invalidating refresh tokens which we'd never really be notified of...).

Note that Ecobee did say somewhere that once they make this switch that OLD refresh tokens will continue to work for some undisclosed amount of time, so you'll likely have to relink anyway come December or January to get a "new style" token set... its unclear if they meant the first time you refresh with one of those it'll issue new token types or continue to issue old ones.

Don't worry though, I actively use my own code here too, if this breaks in December I'll feel it and get it fixed quickly. 😄

**Comment by Gruski** [comment]
Sounds good. My tokens failed again 5 days after I redid them and had to relink again. They must be messing around with the system.

**Comment by i8beef** [comment]
A couple of ideas on that:

1. You can add logging around the token read / write Funcs you pass in so you can see in your logs when those happen... if, for instance, you saw two writes relatively close to each other (like a second or two) that could be indicative of some issue around the locking / token timestamp storage, etc.
2. If you catch ApiAuthException around any call, it will have an "Error" property on it that is a deserialized representation of the Ecobee response. Logging those details could be helpful if you continue to have issues around the refresh token to see if Ecobee things something is wrong.

Like I said, I've seen it happen, but have never caught anything in logs or anything that was helpful. Since token storage is also on the caller here, it can be useful to look there for any way you could lose a token update midstream. It would have to be something like Ecobee processed the token request just fine, but something failed in between that response and the write of the token to persistence, so the next time it attempted to make a call it would still get the same token, try and refresh again, and fail since it had already been used.

In MY code, that would leave (a) the framework failing to read response streams (unlikely), (b) deserialization errors (unlikely as all auth token responses would fail, and deserialization of errors would imply the refresh token request failed anyway, so also unlikely), (c) request timeout (100 seconds by default) AFTER the request has been received by Ecobee, but BEFORE it responds (edge case of edge cases here), or (d) an issue in your passed token storage Func.

I'll keep an eye open on mine if I get invalidated in the future too and see if anything gets captured in my logs around such events.

**Comment by Gruski** [comment]
This is a permanent issue now. After entering the pin it still complains of invalid tokens even after re-adding the application.

**Comment by i8beef** [comment]
I just deleted my tokens and reconnected just fine. Im still not able to reproduce any issue here.

**Comment by i8beef** [comment]
Did your problem eventually resolve?

**Comment by Gruski** [comment]
Never got around into looking at it, in the depth needed. Will do at my next opportunity.

**Comment by i8beef** [comment]
Closing as stale

**Comment by Gruski** [comment]
Got it working but for some reason the change temperature call only works on my dev machine and errors out in your lib In production. All other calls are fine on both. I am thinking your change might be using a library that I have on dev but not in prod. Can you guess what that might be?

**Comment by i8beef** [comment]
I haven't actually changed anything, as their changes didn't require anything. There WAS an update a while back where serialization contracts needed to allow all value types to be nullable, which could have caused issues with individual calls failing before based on what contract was being used, but it would have been obvious in the error that this was the case.
