### ISSUE TITLE
FileLoadException: Could not load file or assembly 'Newtonsoft.Json'

### ISSUE THREAD

**Issue by Perecli** [i8beef/Ecobee#5]
Having this problem again where my app complains about 'Newtonsoft.Json'. 

FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

Remember I had fixed it before by changing my app from .Net Framework to .Net Standard but as I started pulling in libraries that I needed, .Net Standard was really breaking them so had to move my project back to .NET framework. 

I tried adding this in the app.config but it instead it now gives me two errors one for v11.0.0.0 and one for v11.0.1.0:

```
    <runtime>
        <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
            <dependentAssembly>
                <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
                <bindingRedirect oldVersion="0.0.0.0-11.0.1.0" newVersion="11.0.1.0" />
            </dependentAssembly>
        </assemblyBinding>
    </runtime>
```

I also added a nuget package reference to Newtonsoft.Json v11.0.1.0 in my project and still.
Any ideas?

**Comment by Perecli** [comment]
Is it possible for you to release a version of you library in .NET framework? This will probably solve the issue since a had a whole bunch of similar problems with other libraries when my project was targeting .NET standard. Those went away when I went back to .NET framework.

**Comment by i8beef** [comment]
.NET Standard is the way forward for the ecosystem at this point, so that would be a step backward. I can confirm that the NuGet package works just fine on a 4.6.1 framework project, so I'm confident in the implementation here. 

The error in question means that your project is referencing an old version of the Json.NET library somewhere in your app and its conflicting. Likely if you look in your bin directory, you'll find the version of the library that is being copied is not the one you are expecting. In these cases, you have to look at all of the references across all your projects and find the mismatch. If its a NUGET mismatch, you can actually right click on the solution and go to "Manage nuget packages", and it'll have a new tab at the top called "Consolidate" that will let you make sure the same version of the package is referenced across all your projects. If you manually added references to your projects though (note: you almost NEVER want to do that for this reason) then you are going to have to manually go check the version on the reference and remove it.

The assemblyBinding redirects are a hack that your top level application applies to make sure that any dependencies that need lower versions forward their calls to the newer version. If THAT is failing, I'm willing to bet your bad reference is in your top level application.

**Comment by Perecli** [comment]
I striped my project to nothing. No external assemblies, no nuget packages. No references to Neutonsoft. Nothing but a bare new project with no references added other than your lib and the default .NET references added by VS when creating a new project. I stripped my code down to a ridiculously looking few lines of code just enough to make a call to ecobee server. It still fails. The only conflict left possible is in your lib or within VB.NET itself.

Here is a link to this test harness. I would greatly appreciate it if you could look at it.
https://files.argowin.com/test.zip

**Comment by i8beef** [comment]
It appears that this is a known issue that you just have to deal with: https://www.hanselman.com/blog/ReferencingNETStandardAssembliesFromBothNETCoreAndNETFramework.aspx

Basically, if you are referencing a .NET Standard project from a Framework project in a single solution, dependencies do NOT flow the same way they would in an all-framework or all-core solution. 

By far your simplest answer is use NuGet here, because it's going to just handle all this for you. Otherwise you should be able to fix this by adding the NuGet reference for Newtonsoft.Json to any calling projects, or jumping though the hoops Scott mentions there of changing your project format, but that seems pretty hairy if you don't have a decent grasp of what it's doing.
